import Navbar from '../components/navbar';
import Footer from '../components/footer';
import Head from 'next/head';

interface Props {
  children: React.ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <>
      {/* head */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Navbar />

      {/* main */}
      <main className="max-w-screen-xl mx-auto px-[1rem] min-h-[80vh]">{children}</main>

      {/* footer */}
      <Footer />
    </>
  );
};

export default Layout;
